on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - uses: actions/checkout@v3
      - run: apk add openssh-client rsync
      - run: eval $(ssh-agent -s)
      - run: mkdir -p ~/.ssh
      - run: chmod 700 ~/.ssh
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: |
          rsync -avz -e "ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" --delete \
          4aeb3f9d-ad00-4996-b273-fab366d7ce33.JPG \
          apple-touch-icon.png \
          index.html \
          github-ci@daycounter.runepiper.de:/var/www/html/daycounter.runepiper.de
